<?php
/**
 * 各个平台站点配置
 */

defined('ZF_DOMAIN_SUFFIX') || define('ZF_DOMAIN_SUFFIX', env('ZF_DOMAIN_SUFFIX')); // zaful站点主域名

return [
    'zf-pc' => [
        'domain' => [
            'ZF'   => 'https://www' . ZF_DOMAIN_SUFFIX,
            'ZFES' => 'https://es' . ZF_DOMAIN_SUFFIX,
            'ZFFR' => 'https://fr' . ZF_DOMAIN_SUFFIX,
            'ZFDE' => 'https://de' . ZF_DOMAIN_SUFFIX,
            'ZFIE' => 'https://eur' . ZF_DOMAIN_SUFFIX,
            'ZFNZ' => 'https://nz' . ZF_DOMAIN_SUFFIX,
            'ZFGB' => 'https://uk' . ZF_DOMAIN_SUFFIX,
            'ZFCA' => 'https://ca' . ZF_DOMAIN_SUFFIX,
            'ZFBE' => 'https://be' . ZF_DOMAIN_SUFFIX,
            'ZFCH' => 'https://ch' . ZF_DOMAIN_SUFFIX,
            'ZFPH' => 'https://ph' . ZF_DOMAIN_SUFFIX,
            'ZFIN' => 'https://in' . ZF_DOMAIN_SUFFIX,
            'ZFSG' => 'https://sg' . ZF_DOMAIN_SUFFIX,
            'ZFMY' => 'https://my' . ZF_DOMAIN_SUFFIX,
            'ZFAU' => 'https://au' . ZF_DOMAIN_SUFFIX,
            'ZFAT' => 'https://at' . ZF_DOMAIN_SUFFIX,
            'ZFMX' => 'https://latam' . ZF_DOMAIN_SUFFIX,
            'ZFZA' => 'https://za' . ZF_DOMAIN_SUFFIX,
            'ZFBR' => 'https://br' . ZF_DOMAIN_SUFFIX,
            'ZFTH' => 'https://th' . ZF_DOMAIN_SUFFIX,
            'ZFID' => 'https://id' . ZF_DOMAIN_SUFFIX,
            'ZFTW' => 'https://tw' . ZF_DOMAIN_SUFFIX ,
            'ZFAR' => 'https://ar' . ZF_DOMAIN_SUFFIX,
            'ZFIT' => 'https://it' . ZF_DOMAIN_SUFFIX,
            'ZFIL' => 'https://il' . ZF_DOMAIN_SUFFIX,
            'ZFRU' => 'https://ru' . ZF_DOMAIN_SUFFIX ,
            'ZFHK' => 'https://hk' . ZF_DOMAIN_SUFFIX,
            'ZFTR' => 'https://tr' . ZF_DOMAIN_SUFFIX,
            'ZFMX01' => 'https://mx' . ZF_DOMAIN_SUFFIX,
            'ZFRO' => 'https://ro' . ZF_DOMAIN_SUFFIX,
            'ZFJP' => 'https://jp' . ZF_DOMAIN_SUFFIX,
            'ZFVN' => 'https://vn' . ZF_DOMAIN_SUFFIX
        ]
    ],
    'zf-wap' => [
        'domain' => [
            'ZF'   => 'https://m' . ZF_DOMAIN_SUFFIX,
            'ZFES' => 'https://es-m' . ZF_DOMAIN_SUFFIX,
            'ZFFR' => 'https://fr-m' . ZF_DOMAIN_SUFFIX,
            'ZFDE' => 'https://de-m' . ZF_DOMAIN_SUFFIX,
            'ZFIE' => 'https://eur-m' . ZF_DOMAIN_SUFFIX,
            'ZFNZ' => 'https://nz-m' . ZF_DOMAIN_SUFFIX,
            'ZFGB' => 'https://uk-m' . ZF_DOMAIN_SUFFIX,
            'ZFCA' => 'https://ca-m' . ZF_DOMAIN_SUFFIX,
            'ZFBE' => 'https://be-m' . ZF_DOMAIN_SUFFIX,
            'ZFCH' => 'https://ch-m' . ZF_DOMAIN_SUFFIX,
            'ZFPH' => 'https://ph-m' . ZF_DOMAIN_SUFFIX,
            'ZFIN' => 'https://in-m' . ZF_DOMAIN_SUFFIX,
            'ZFSG' => 'https://sg-m' . ZF_DOMAIN_SUFFIX,
            'ZFMY' => 'https://my-m' . ZF_DOMAIN_SUFFIX,
            'ZFAU' => 'https://au-m' . ZF_DOMAIN_SUFFIX,
            'ZFAT' => 'https://at-m' . ZF_DOMAIN_SUFFIX,
            'ZFMX' => 'https://latam-m' . ZF_DOMAIN_SUFFIX,
            'ZFZA' => 'https://za-m' . ZF_DOMAIN_SUFFIX,
            'ZFBR' => 'https://br-m' . ZF_DOMAIN_SUFFIX,
            'ZFTH' => 'https://th-m' . ZF_DOMAIN_SUFFIX,
            'ZFID' => 'https://id-m' . ZF_DOMAIN_SUFFIX,
            'ZFTW' => 'https://tw-m' . ZF_DOMAIN_SUFFIX ,
            'ZFAR' => 'https://ar-m' . ZF_DOMAIN_SUFFIX,
            'ZFIT' => 'https://it-m' . ZF_DOMAIN_SUFFIX,
            'ZFIL' => 'https://il-m' . ZF_DOMAIN_SUFFIX,
            'ZFRU' => 'https://ru-m' . ZF_DOMAIN_SUFFIX ,
            'ZFHK' => 'https://hk-m' . ZF_DOMAIN_SUFFIX,
            'ZFTR' => 'https://tr-m' . ZF_DOMAIN_SUFFIX,
            'ZFMX01' => 'https://mx-m' . ZF_DOMAIN_SUFFIX,
            'ZFRO' => 'https://ro-m' . ZF_DOMAIN_SUFFIX,
            'ZFJP' => 'https://jp-m' . ZF_DOMAIN_SUFFIX,
            'ZFVN' => 'https://vn-m' . ZF_DOMAIN_SUFFIX
        ]
    ],
    'zf-app' => [
        'domain' => [
            'ZF'   => 'https://m' . ZF_DOMAIN_SUFFIX,
            'ZFES' => 'https://es-m' . ZF_DOMAIN_SUFFIX,
            'ZFFR' => 'https://fr-m' . ZF_DOMAIN_SUFFIX,
            'ZFDE' => 'https://de-m' . ZF_DOMAIN_SUFFIX,
            'ZFIE' => 'https://eur-m' . ZF_DOMAIN_SUFFIX,
            'ZFNZ' => 'https://nz-m' . ZF_DOMAIN_SUFFIX,
            'ZFGB' => 'https://uk-m' . ZF_DOMAIN_SUFFIX,
            'ZFCA' => 'https://ca-m' . ZF_DOMAIN_SUFFIX,
            'ZFBE' => 'https://be-m' . ZF_DOMAIN_SUFFIX,
            'ZFCH' => 'https://ch-m' . ZF_DOMAIN_SUFFIX,
            'ZFPH' => 'https://ph-m' . ZF_DOMAIN_SUFFIX,
            'ZFIN' => 'https://in-m' . ZF_DOMAIN_SUFFIX,
            'ZFSG' => 'https://sg-m' . ZF_DOMAIN_SUFFIX,
            'ZFMY' => 'https://my-m' . ZF_DOMAIN_SUFFIX,
            'ZFAU' => 'https://au-m' . ZF_DOMAIN_SUFFIX,
            'ZFAT' => 'https://at-m' . ZF_DOMAIN_SUFFIX,
            'ZFMX' => 'https://latam-m' . ZF_DOMAIN_SUFFIX,
            'ZFZA' => 'https://za-m' . ZF_DOMAIN_SUFFIX,
            'ZFBR' => 'https://br-m' . ZF_DOMAIN_SUFFIX,
            'ZFTH' => 'https://th-m' . ZF_DOMAIN_SUFFIX,
            'ZFID' => 'https://id-m' . ZF_DOMAIN_SUFFIX,
            'ZFTW' => 'https://tw-m' . ZF_DOMAIN_SUFFIX,
            'ZFAR' => 'https://ar-m' . ZF_DOMAIN_SUFFIX,
            'ZFIT' => 'https://it-m' . ZF_DOMAIN_SUFFIX,
            'ZFIL' => 'https://il-m' . ZF_DOMAIN_SUFFIX,
            'ZFRU' => 'https://ru-m' . ZF_DOMAIN_SUFFIX,
            'ZFTR' => 'https://tr-m' . ZF_DOMAIN_SUFFIX,
            'ZFVN' => 'http://vn-m' . ZF_DOMAIN_SUFFIX,
            'ZFJP' => 'https://jp-m' . ZF_DOMAIN_SUFFIX,
            'ZFHK' => 'https://hk-m' . ZF_DOMAIN_SUFFIX,
            'ZFMX01' => 'https://mx-m' . ZF_DOMAIN_SUFFIX,
            'ZFRO' => 'https://ro-m' . ZF_DOMAIN_SUFFIX,
        ]
    ],
];
